### ISSUE TITLE
feature request: sliceEditor (browser only)

### ISSUE THREAD

**Issue by s-a** [mohayonao/ciseaux#16]
Visualization of slices in a separate spectrum canvas as vertical lines which is 2 way bound to the tape instance.  

 - Activate a slice: Mouse Click;  
 - Move a slice: Keyboard left (move one tick);  
 - Move a slice faster: shift+Keyboard left (move 10 ticks);

**Comment by mohayonao** [comment]
No. The online demo aims to present features of library.
I should discriminate between features of Ciseaux and features of an application that uses Ciseaux.

I hope that you make your nice ideas come true on your web site.

**Comment by s-a** [comment]
:) that sounds reasonable
