### ISSUE TITLE
tape.render returns invalid ArrayBuffer?

### ISSUE THREAD

**Issue by s-a** [mohayonao/ciseaux#18]
I get an error while calling ```audioContext.decodeAudioData```.

DOMException: Failed to execute 'decodeAudioData' on 'AudioContext': invalid ArrayBuffer for audioData.

    Device.prototype.load = function(url, done) {
      var self = this;
      var processData = function  (arraybuffer) {
        
        self.audioContext.decodeAudioData(arraybuffer, function(decodedData) {
          debugger;
          //self.rawData = decodedData;
          self.tape = new Ciseaux.Tape(decodedData);
          self.renderAudio(function() {
            self.setLoadingProgressIndicator(false);
            self.initializeSpectrum();
            if (done){
              $.proxy(done, self)();
            }
          });
        });
      }
      if (typeof url === 'string'){
        this.get(url, function(arraybuffer) {
          processData(arraybuffer);
        });
      } else {
        this.renderAudio(function  (arraybuffer) {
          processData(arraybuffer);
        })
      }
    };

    Device.prototype.renderAudio = function(done) {
      var self = this;
      this.tape.render(this.audioContext, 2).then(function(audioBuffer) {
        self.audioBuffer = audioBuffer;
        if (done){
          $.proxy(done, self)(audioBuffer);
        }
      });
    };

where this.tape is produced like with this command  
```var tape = tape3.slice(0, 0.5).concat(Ciseaux.silence(0.5)).loop(4);```

While your demos at http://mohayonao.github.io/ciseaux/ are working with this code I guess I do something wrong. Are you using latest version ```0.1.8``` there?

**Comment by mohayonao** [comment]
tape.render returns `Promise<`**`AudioBuffer`**`>`

**Comment by s-a** [comment]
ups . Thanks!
